# Content {{{1
# General {{{2
title: História da Arquitetura e da Arte I
author: Pedro P. Palazzo
email: palazzo@unb.br
description: >-
  História do urbanismo, da arquitetura e da arte no contexto de seus
  condicionantes sociais, econômicos e políticos, desde os primórdios da
  civilização até o gótico.
baseurl: "/tau0005"
url: "https://p3palazzo.github.io"
lang: pt-BR

# Collections {{{2
collections:
  aula:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: page

# Build settings {{{1
# Theme {{{2
theme: tufte-pandoc-jekyll
header_pages:
  - README.md
minima:
  date_format : "%e %B %Y"
  social_links:
    twitter   : p3palazzo
    github    : p3palazzo
    instagram : arqtrad

# Build parameters {{{2
markdown: Pandoc
pandoc:
  extensions:
    - defaults: "_spec/html.yaml"
    - section-divs
#permalink: pretty
readme_index:
  enabled         : true
  remove_originals: true
  with_frontmatter: true
relative_links:
  enabled         : true
  collections     : true
sass_dir:
  load_paths:
    - _sass
    - _sass/minima
    - assets
    - assets/css
    - reveal.js/css/theme/template
timezone: America/Sao_Paulo

# Plugins {{{1
plugins:
  - jekyll-feed
  - jekyll-pandoc
  - jekyll-sitemap
  - jekyll-seo-tag
  #- kramdown
    # The following plugins are always used by GH-Pages
  - jekyll-coffeescript
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-relative-links
  # Plugins incompatible with GitHub Pages
  #- jekyll-scholar

# Keep and Exclude {{{1
exclude:
  - LICENSE
  - Makefile
  - biblio.bib
  - outcomes.csv
  - reveal.js
keep_files:
  - slides
  - reveal.js
# vim: set foldmethod=marker :
