# General
title: História da Arquitetura e da Arte I
author: Pedro P. Palazzo
email: palazzo@unb.br
description: >-
  História do urbanismo, da arquitetura e da arte no contexto de seus
  condicionantes sociais, econômicos e políticos, desde os primórdios da
  civilização até o gótico.
baseurl: "/tau0005"
url: "https://palazzo.arq.br"
lang: pt-BR

# Content
header_includes:
  - <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">
  - <link rel="stylesheet" href="https://use.fontawesome.com/9303e96850.css">

# Collections
collections:
  aula:
    output: true
    permalink: /:collection/:name/
  plano:
    output: true
    permalink: /:collection/:name/
    order:
      - por-que-historia.md
      - sobre-disciplina.md
      - objetivos.md
      - metodologia.md
      - apoio.md
      - avalia.md
      - bibliografia.md
  trab:
    output: true
    permalink: /:collection/:name/
    order:
      - processo.md
      - vernacular.md
      - quincunx.md
      - analitico.md

defaults:
  - scope:
      path: ""
    values:
      layout: page

# Theme
theme: tufte-pandoc-jekyll

# Build parameters
markdown: Pandoc
pandoc:
  extensions:
    - defaults: "_spec/html.yaml"
    - csl: "_csl/chicago-fullnote-bibliography-with-ibid.csl"
    - section-divs
permalink: pretty
relative_links:
  enabled: true
  collections: true
sass_dir:
  load_paths:
    - _sass
    - assets
    - assets/css
    - assets/css-slides
    - reveal.js/css/theme/template
scholar:
  locale: pt-BR
  sort_by: author,year
  order: ascending,descending
  style: "chicago-fullnote-bibliography-with-ibid"
timezone: America/Sao_Paulo

# Plugins
plugins:
  - jekyll-data
  - jekyll-feed
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-pandoc
  - jekyll-relative-links
  - jekyll-scholar
  - jekyll-seo-tag
  - jekyll-sitemap

# Keep and Exclude
exclude:
  - LICENSE
  - Makefile
  - README.md
  - "*.fdb_latexmk"
  - "*.run.xml"
keep_files:
  - .git
  - slides
