# General
title: História da Arquitetura e da Arte I
author: Pedro P. Palazzo
email: palazzo@unb.br
description: >-
  História do urbanismo, da arquitetura e da arte no contexto de seus
  condicionantes sociais, econômicos e políticos, desde os primórdios da
  civilização até o gótico.
baseurl: "/tau0005"
url: "https://palazzo.arq.br"
lang: pt-BR

# Content
header_includes:
  - <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">
  - <link rel="stylesheet" href="https://use.fontawesome.com/9303e96850.css">

# Collections
collections:
  aula:
    output: true
    permalink: /:collection/:name/

defaults:
  -
    scope:
      path: ""
    values:
      layout: page

# Theme
theme: tufte-pandoc-jekyll

# Build parameters
markdown: Pandoc
pandoc:
  extensions:
    - defaults    : "_spec/html.yaml"
    - section-divs
permalink         : pretty
readme_index:
  enabled         : true
  remove_originals: true
  with_frontmatter: true
relative_links:
  enabled         : true
  collections     : true
sass_dir:
  load_paths:
    - _sass
    - assets
    - assets/css
    - assets/css-slides
    - reveal.js/css/theme/template
timezone          : America/Sao_Paulo

# Plugins
plugins:
  - jekyll-data
  - jekyll-feed
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-pandoc
  - jekyll-relative-links
  - jekyll-scholar
  - jekyll-seo-tag
  - jekyll-sitemap

# Keep and Exclude
exclude:
  - LICENSE
  - Makefile
  - README.md
  - "default.*"
  - "*.fdb_latexmk"
  - "*.run.xml"
keep_files:
  - .git
  - slides
