# General
title: História da Arquitetura e da Arte I
author: Pedro P. Palazzo
email: palazzo@unb.br
description: >-
  História do urbanismo, da arquitetura e da arte no contexto de seus
  condicionantes sociais, econômicos e políticos, desde os primórdios da
  civilização até o gótico.
baseurl: "/tau0005"
url: "https://palazzo.arq.br"
lang: pt-BR

# Content
header_includes:
  - <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">
  - <script src="https://kit.fontawesome.com/eddf3d9a63.js" crossorigin="anonymous"></script>

# Collections
collections:
  aula:
    output: true
    permalink: /:collection/:name/
  plano:
    output: true
    permalink: /:collection/:name/
    order:
      - por-que-historia.md
      - sobre-disciplina.md
      - objetivos.md
      - metodologia.md
      - apoio.md
      - avalia.md
      - bibliografia.md
  trabalho:
    output: true
    permalink: /:collection/:name/
    order:
      - processo.md
      - vernacular.md
      - quincunx.md
      - analitico.md

defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: "plano"
    values:
      include_before: |
        <nav id="main-nav">
          <a class="icons" href="/tau0005/"><i class="far fa-calendar-alt fa-2x" title="Programa"></i></a>
          <a class="icons" href="/tau0005/plano/objetivos/"><i class="fas fa-crosshairs fa-2x" title="Objetivos"></i></a>
          <a class="icons" href="/tau0005/plano/metodologia/"><i class="fas fa-cog fa-2x" title="Metodologia"></i></a>
          <a class="icons" href="/tau0005/plano/bibliografia/"><i class="fas fa-book fa-2x" title="Bibliografia"></i></a>
          <a class="icons" href="/tau0005/plano/avalia/"><i class="fas fa-pencil-alt fa-2x" title="Avaliação"></i></a>
          <!--<a class="icons" target="_blank" href="https://teams.microsoft.com/l/meetup-join/19%3aUsJdAp730q1MDQwmuqPX1xrVCzihj-ZgM2WnodRSnmw1%40thread.tacv2/1626120571713?context=%7b%22Tid%22%3a%22ec359ba1-630b-4d2b-b833-c8e6d48f8059%22%2c%22Oid%22%3a%22a23e04dd-338a-4a2f-95ba-cb5d1a864e69%22%7d"><i class="fab fa-microsoft fa-2x" title="Microsoft Teams"></i></a>-->
          <!--<a class="icons" target="_top" href="https://aprender3.unb.br/course/view.php?id=8552"><i class="ai ai-moodle ai-2x" title="Moodle (Aprender 3)"></i></a>-->
        </nav>

# Theme
theme: tufte-pandoc-jekyll

# Build parameters
markdown: Pandoc
pandoc:
  extensions:
    - defaults: "_spec/html.yaml"
    - csl: "https://raw.githubusercontent.com/citation-style-language/styles/master/chicago-note-bibliography-with-ibid.csl"
    - section-divs
permalink: pretty
relative_links:
  enabled: true
  collections: true
sass_dir:
  load_paths:
    - _sass
    - assets
    - assets/css
    - assets/css-slides
    - reveal.js/css/theme/template
scholar:
  locale: pt-BR
  sort_by: author,editor,year
  order: ascending,ascending,descending
  style: "chicago-fullnote-bibliography-with-ibid"
timezone: America/Sao_Paulo

# Plugins
plugins:
  - jekyll-data
  - jekyll-feed
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-pandoc
  - jekyll-relative-links
  - jekyll-scholar
  - jekyll-seo-tag
  - jekyll-sitemap

# Keep and Exclude
exclude:
  - LICENSE
  - Makefile
  - README.md
  - "*.fdb_latexmk"
  - "*.run.xml"
keep_files:
  - .git
