name: Build
on:
  pull_request:
  push:
    branches: [ master ]
jobs:
  slides:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Test build website
      run: make .slides
    - name: Upload website
      uses: actions/upload-artifact@v2
      with:
        name: slides
        path: '_site/slides/*'
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Test build website
      run: >
        sudo apt-get install
        pandoc=2.11.3.2
        pandoc-crossref=0.3.9.0
        && wget https://github.com/jez/pandoc-sidenote/releases/download/0.22.1/pandoc-sidenote-0.22.1.zip
        && unzip pandoc-sidenote-0.22.1.zip
        && mv pandoc-sidenote /usr/local/bin/
        && bundle exec jekyll build
    - name: Upload website
      uses: actions/upload-artifact@v2
      with:
        name: site
        path: '_site/*'
  commit:
    runs-on: ubuntu-latest
    needs: [ slides, build ]
    if: github.event_name == 'push' && github.repository == 'p3palazzo/tau0005'
    env:
      commit_message: ${{ github.event.head_commit.message }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref : 'gh-pages'
        submodules: 'recursive'
    - name: Download site
      uses: actions/download-artifact@v2
      with:
        name: site
        path: ${{ github.workspace }}/
    - name: Download notas
      uses: actions/download-artifact@v2
      with:
        name: notas
        path: ${{ github.workspace }}/
    - name: Download slides
      uses: actions/download-artifact@v2
      with:
        name: slides
        path: ${{ github.workspace }}/
    - name: Commit changes to gh-pages branch
      run: |
        cd ${{ github.workspace }}
        git config --local user.email "runner@github.com"
        git config --local user.name  "Automated build"
        git add .
        git commit -m "${{ env.commit_message }}" -a || git status
        git pull --ff-only
        git push
